# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookBook
  target 'CookBookTests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'

  end

end
