# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookBook
    pod 'Contentful'
  	pod 'SDWebImage'
    pod 'Down'
    pod 'iOSSnapshotTestCase'

    target 'CookBookTests' do
      inherit! :search_paths
    end

end
